<!--Author      : @afvndo -->
<?php

  define ('BROWSER', $this->_system->_browser);  
  
  define ('LOBIADMIN',$_SESSION["PORTAL_LOBIADMIN_LINK"]);
  
  define ('PORTAL_LINK',$_SESSION["PORTAL_LINK"]);
  
  define ('PORTAL_JS_LINK',$_SESSION["PORTAL_JS_SCRIPTS_LINK"]);
  
  define ('PORTAL_DOMINIO_LINK',$_SESSION["PORTAL_DOMINIO_LINK"]);

?>
<div id='ntfm000100'>

	<div id="id-nav-tabs">
		 <!--Nav tabs--> 
		<ul class="nav nav-tabs" role="tablist">
			<li class="active">
				<a href="#id-nav-tabs .home" role="tab" data-toggle="tab">
					<i class="fa fa-home text-cyan-dark"></i>
					Home 
					<span class="badge badge-xs bg-red-light">12</span>
				</a>
			</li>
			<li>
				<a href="#id-nav-tabs .messages" role="tab" data-toggle="tab">
					<i class="fa fa-envelope text-cyan-dark"></i>
					Messages
					<span class="badge badge-xs bg-orange-dark">6</span>
				</a>
			</li>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-cog text-cyan-dark"></i>
					Settings <span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#id-nav-tabs .profile" data-toggle="tab">Lorem</a></li>
					<li><a href="#id-nav-tabs .settings" data-toggle="tab">Ipsum</a></li>
				</ul>
			</li>
		</ul>

		 <!--Tab panes--> 
		<div class="tab-content bg-white padding-15">
			<div class="tab-pane home active fixoH300">
			   <div class="table-responsive">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>#</th>
								<th>Project Name</th>
								<th>Progress</th>
								<th>Status</th>
								<th>Users</th>
								<th>Testing</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">1</th>
								<td>Project 1</td>
								<td>
									<div class="progress progress-xs">
										<div class="progress-bar progress-bar-striped progress-bar-warning active" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"><span class="sr-only">20% Complete</span></div>
									</div>
								</td>
								<td>
									<label class="switch-inline switch-xs" data-toggle="tooltip" data-title="Change project status">
										<input type="checkbox" checked>
										<i></i>
									</label>
								</td>
								<td>
									<img src="img/users/5.jpg" width="40" alt="" class="img-circle"/>
									<img src="img/users/1.jpg" width="40" alt="" class="img-circle"/>
									<img src="img/users/4.jpg" width="40" alt="" class="img-circle"/>
									<img src="img/users/2.jpg" width="40" alt="" class="img-circle"/>
								</td>
								<td>
									<label class="switch-outline switch-xs">
										<input type="checkbox" checked>
										<i></i>
									</label>
								</td>
								<td>
									<button class="btn btn-info btn-pretty btn-xs"><i class="fa fa-folder-o"></i> Open</button>
									<button class="btn btn-info btn-pretty btn-xs"><i class="fa fa-edit"></i> Edit</button>
								</td>
							</tr>
							<tr>
								<th scope="row">2</th>
								<td>Project 2</td>
								<td>
									<div class="progress progress-xs">
										<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"><span class="sr-only">50% Complete</span></div>
									</div>
								</td>
								<td>
									<label class="switch-inline switch-xs" data-toggle="tooltip" data-title="Change project status">
										<input type="checkbox" checked>
										<i></i>
									</label>
								</td>
								<td>
									<img src="img/users/1.jpg" width="40" alt="" class="img-circle"/>
									<img src="img/users/2.jpg" width="40" alt="" class="img-circle"/>
									<img src="img/users/4.jpg" width="40" alt="" class="img-circle"/>
								</td>
								<td>
									<label class="switch-outline switch-xs">
										<input type="checkbox">
										<i></i>
									</label>
								</td>
								<td>
									<button class="btn btn-info btn-pretty btn-xs"><i class="fa fa-folder-o"></i> Open</button>
									<button class="btn btn-info btn-pretty btn-xs"><i class="fa fa-edit"></i> Edit</button>
								</td>
							</tr>
							<tr>
								<th scope="row">3</th>
								<td>Another project</td>
								<td>
									<div class="progress progress-xs">
										<div class="progress-bar progress-bar-striped active progress-bar-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%"><span class="sr-only">90% Complete</span></div>
									</div>
								</td>
								<td>
									<label class="switch-inline switch-xs" data-toggle="tooltip" data-title="Change project status">
										<input type="checkbox" checked>
										<i></i>
									</label>
								</td>
								<td>
									<img src="img/users/3.jpg" width="40" alt="" class="img-circle"/>
								</td>
								<td>
									<label class="switch-outline switch-xs">
										<input type="checkbox" checked>
										<i></i>
									</label>
								</td>
								<td>
									<button class="btn btn-info btn-pretty btn-xs"><i class="fa fa-folder-o"></i> Open</button>
									<button class="btn btn-info btn-pretty btn-xs"><i class="fa fa-edit"></i> Edit</button>
								</td>
							</tr>
						</tbody>
					</table>
				</div>				
			</div>
			<div class="tab-pane messages fixoH300">
				Lorem ipsum dolor sit amet failed ditties restrictions eventide lacked rubies. Chips authors waved turtle fingers cave, lamp pay restrictions quatrains, yet swedenborg, greek sallow war. Followed failed rubies plunge stalwart erred, mild brute. Ibn gravitate yet mauris greek certain pay, spoil restrictions smite martin lamp mild.
			</div>
			<div class="tab-pane profile fixoH300">
				Lorem ipsum dolor sit amet lynx forth retreats solve rasping conifers. Polls copying emerson spell nooks numb spray, cut awful, cathedrals inaccurate tardy, savage furies fanning. Armies drugs emerson forth grate crack behmen willow orbs, strewing cathedrals, shoes sting. Gutenberg nulla ye, privacies pere shard retreats proffered fanning nooks provision rays. Ye sonnet hammered, smudge grate, crown http angel. Armies locked numb savage awful ye, foremost crack jot.
			</div>
			<div class="tab-pane settings fixoH300">
				Lorem ipsum dolor sit amet grassy oak maker, saviour, fulfilled waft darkened commodore. Knaves redistribute gladiators looming, fool dirs ka. Sudden nec looming rags shade fool, marked disperse. Proprietary halls shalt electronically spangled back slinks she trod. Generations satellites fierce sinks at, few grassy donec ka honours separate. Proprietary crusader panther according, vanilla nec slender turtle slay separate creating swept. At marked proprietary slender pharetra shalt woodland, back brood rabbit boon ka pyramid fierce. Saviour slender woodland brood given rags dirs our. Shade faithful creating panther donec opportunity sudden. Cromwell fool vanquished, panther satellites crumbs marble waft given honours.
			</div>
		</div>
	</div>


<script>
   $(function () {
	   // Executando os scripts dessa .phtml uhuuuu

	   // Atualizando dados para o programa
       $("#prg_titulo").html("<?php echo $view_page_header;?>");
	   
	   // Forcando atualizacao do Breadcrumb
	   var lobiAdmin = $('body').data('lobiAdmin');
	   lobiAdmin.setBreadcrumbs([{texto : "<?php echo $view_page_header;?>", href: "NONE", cssicon: "<?php echo $view_page_icone;?>"}]);
   });
</script>
</div>
